Transform: AWS::Serverless-2016-10-31

Description: "Parameters to connect lambdas to secret manager service"

Resources:

  LambdaLayerParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AWS::StackName}_lambda_layer
      Type: String
      Value: "NA"

  LambdaLayerParameterAuxiliar:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub ${AWS::StackName}_auxiliar_layer
      Type: String
      Value: "NA"

Outputs:
  LambdaLayerParameter:
    Value: !Ref LambdaLayerParameter
    Export:
      Name: LambdaLayerParameter

  LambdaLayerParameterAuxiliar:
    Value: !Ref LambdaLayerParameterAuxiliar
    Export:
      Name: LambdaLayerParameterAuxiliar